export {
	LegacyAlertDialog,
	LegacyAlertDialogButton,
	type LegacyAlertDialogButtonProps,
	LegacyAlertDialogClose,
	LegacyAlertDialogContent,
	type LegacyAlertDialogContentProps,
	LegacyAlertDialogDescription,
	type LegacyAlertDialogDescriptionProps,
	LegacyAlertDialogFooter,
	type LegacyAlertDialogFooterProps,
	LegacyAlertDialogHeader,
	type LegacyAlertDialogHeaderProps,
	LegacyAlertDialogPanel,
	type LegacyAlertDialogPanelProps,
	type LegacyAlertDialogProps,
	LegacyAlertDialogTitle,
	type LegacyAlertDialogTitleProps,
	LegacyAlertDialogTrigger,
} from "../legacy-alert-dialog";
