export {
	IosAlertDialog,
	IosAlertDialogButton,
	type IosAlertDialogButtonProps,
	IosAlertDialogClose,
	IosAlertDialogContent,
	type IosAlertDialogContentProps,
	IosAlertDialogDescription,
	type IosAlertDialogDescriptionProps,
	IosAlertDialogFooter,
	type IosAlertDialogFooterProps,
	IosAlertDialogHeader,
	type IosAlertDialogHeaderProps,
	IosAlertDialogPanel,
	type IosAlertDialogPanelProps,
	type IosAlertDialogProps,
	IosAlertDialogTitle,
	type IosAlertDialogTitleProps,
	IosAlertDialogTrigger,
} from "../../registry/default/ios-alert-dialog/ios-alert-dialog";
